In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv("../data/credit_risk_dataset_raw.csv")
df.head(20)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
5,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2
6,26,77100,RENT,8.0,EDUCATION,B,35000,12.42,1,0.45,N,3
7,24,78956,RENT,5.0,MEDICAL,B,35000,11.11,1,0.44,N,4
8,24,83000,RENT,8.0,PERSONAL,A,35000,8.90,1,0.42,N,2
9,21,10000,OWN,6.0,VENTURE,D,1600,14.74,1,0.16,N,3
10,22,85000,RENT,6.0,VENTURE,B,35000,10.37,1,0.41,N,4
11,21,10000,OWN,2.0,HOMEIMPROVEMENT,A,4500,8.63,1,0.45,N,2
12,23,95000,RENT,2.0,VENTURE,A,35000,7.90,1,0.37,N,2
13,26,108160,RENT,4.0,EDUCATION,E,35000,18.39,1,0.32,N,4
14,23,115000,RENT,2.0,EDUCATION,A,35000,7.90,0,0.30,N,4
15,23,500000,MORTGAGE,7.0,DEBTCONSOLIDATION,B,30000,10.65,0,0.06,N,3
16,23,120000,RENT,0.0,EDUCATION,A,35000,7.90,0,0.29,N,4
17,23,92111,RENT,7.0,MEDICAL,F,35000,20.25,1,0.32,N,4
18,23,113000,RENT,8.0,DEBTCONSOLIDATION,D,35000,18.25,1,0.31,N,4
19,24,10800,MORTGAGE,8.0,EDUCATION,B,1750,10.99,1,0.16,N,2

In [3]:
print(len(df))

32581

In [4]:
df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [5]:
df.dtypes

person_age                      int64
person_income                   int64
person_home_ownership          object
person_emp_length             float64
loan_intent                    object
loan_grade                     object
loan_amnt                       int64
loan_int_rate                 float64
loan_status                     int64
loan_percent_income           float64
cb_person_default_on_file      object
cb_person_cred_hist_length      int64
dtype: object

In [6]:
df = df.convert_dtypes()

In [7]:
df.dtypes

person_age                             Int64
person_income                          Int64
person_home_ownership         string[python]
person_emp_length                      Int64
loan_intent                   string[python]
loan_grade                    string[python]
loan_amnt                              Int64
loan_int_rate                        Float64
loan_status                            Int64
loan_percent_income                  Float64
cb_person_default_on_file     string[python]
cb_person_cred_hist_length             Int64
dtype: object

In [8]:
for column in df.columns:
    if df[column].dtype == "string":
        df[column] = df[column].astype("object")

In [9]:
df.dtypes

person_age                      Int64
person_income                   Int64
person_home_ownership          object
person_emp_length               Int64
loan_intent                    object
loan_grade                     object
loan_amnt                       Int64
loan_int_rate                 Float64
loan_status                     Int64
loan_percent_income           Float64
cb_person_default_on_file      object
cb_person_cred_hist_length      Int64
dtype: object

In [10]:
df["person_age"].min()

np.int64(20)

In [11]:
df[df["person_age"] == df["person_age"].max()]

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
81,144,250000,RENT,4,VENTURE,C,4800,13.57,0,0.02,N,3
183,144,200000,MORTGAGE,4,EDUCATION,B,6000,11.86,0,0.03,N,2
32297,144,6000000,MORTGAGE,12,PERSONAL,C,5000,12.73,0,0.0,N,25

In [12]:
df["person_emp_length"].min()

np.int64(0)

In [13]:
df["person_emp_length"].max()

np.int64(123)

In [14]:
print(df["person_home_ownership"].unique())
print(df["loan_intent"].unique())
print(df["loan_grade"].unique())
print(df["cb_person_default_on_file"].unique())

['RENT' 'OWN' 'MORTGAGE' 'OTHER']
['PERSONAL' 'EDUCATION' 'MEDICAL' 'VENTURE' 'HOMEIMPROVEMENT'
 'DEBTCONSOLIDATION']
['D' 'B' 'C' 'A' 'E' 'F' 'G']
['Y' 'N']

In [15]:
df[df["person_age"] > 100]

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
81,144,250000,RENT,4,VENTURE,C,4800,13.57,0,0.02,N,3
183,144,200000,MORTGAGE,4,EDUCATION,B,6000,11.86,0,0.03,N,2
575,123,80004,RENT,2,EDUCATION,B,20400,10.25,0,0.25,N,3
747,123,78000,RENT,7,VENTURE,B,20000,<NA>,0,0.26,N,4
32297,144,6000000,MORTGAGE,12,PERSONAL,C,5000,12.73,0,0.0,N,25

In [16]:
df["person_age"].describe()

count     32581.0
mean      27.7346
std      6.348078
min          20.0
25%          23.0
50%          26.0
75%          30.0
max         144.0
Name: person_age, dtype: Float64

In [17]:
df = df.drop(df[df["person_age"] > 100].index)

In [18]:
df[df["loan_int_rate"].isnull()]

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
39,23,71500,RENT,3,DEBTCONSOLIDATION,D,30000,<NA>,1,0.42,N,4
50,24,78000,RENT,4,DEBTCONSOLIDATION,D,30000,<NA>,1,0.38,Y,4
57,23,277000,OWN,3,PERSONAL,A,35000,<NA>,0,0.13,N,4
59,24,12000,OWN,2,VENTURE,E,1750,<NA>,0,0.15,Y,3
62,26,263000,MORTGAGE,0,EDUCATION,B,10000,<NA>,1,0.04,N,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32547,53,4888,OWN,0,VENTURE,C,1400,<NA>,1,0.29,Y,28
32552,65,45900,RENT,2,EDUCATION,C,10000,<NA>,0,0.22,Y,19
32553,54,20000,RENT,2,MEDICAL,C,5000,<NA>,0,0.25,N,28
32569,51,60000,MORTGAGE,1,PERSONAL,A,7500,<NA>,0,0.13,N,23
32570,58,72000,RENT,5,HOMEIMPROVEMENT,B,4500,<NA>,0,0.06,N,23

In [19]:
df[df["person_emp_length"].isnull()]

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
105,22,12600,MORTGAGE,<NA>,PERSONAL,A,2000,5.42,1,0.16,N,4
222,24,185000,MORTGAGE,<NA>,EDUCATION,B,35000,12.42,0,0.19,N,2
379,24,16800,MORTGAGE,<NA>,DEBTCONSOLIDATION,A,3900,<NA>,1,0.23,N,3
407,25,52000,RENT,<NA>,PERSONAL,B,24000,10.74,1,0.46,N,2
408,22,17352,MORTGAGE,<NA>,EDUCATION,C,2250,15.27,0,0.13,Y,3
...,...,...,...,...,...,...,...,...,...,...,...,...
32285,38,12000,OWN,<NA>,EDUCATION,A,4800,7.29,1,0.4,N,12
32328,51,18408,RENT,<NA>,PERSONAL,C,1000,14.65,1,0.05,Y,20
32360,70,39996,RENT,<NA>,MEDICAL,C,3600,15.23,0,0.09,Y,19
32453,56,32400,RENT,<NA>,MEDICAL,A,8575,7.51,0,0.26,N,18
32471,53,54000,RENT,<NA>,MEDICAL,D,10000,14.59,1,0.19,Y,27

In [20]:
imputer = SimpleImputer(strategy="median")
imputer.fit(df[["loan_int_rate", "person_emp_length"]])
df[["loan_int_rate","person_emp_length"]] = imputer.transform(df[["loan_int_rate","person_emp_length"]])

In [21]:
df.isnull().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [22]:
df.dtypes

person_age                      Int64
person_income                   Int64
person_home_ownership          object
person_emp_length             float64
loan_intent                    object
loan_grade                     object
loan_amnt                       Int64
loan_int_rate                 float64
loan_status                     Int64
loan_percent_income           Float64
cb_person_default_on_file      object
cb_person_cred_hist_length      Int64
dtype: object

In [23]:
df["person_emp_length"] = df["person_emp_length"].astype("Int64")
df["loan_int_rate"] = df["loan_int_rate"].astype("Float64")

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32576 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32576 non-null  Int64
 1   person_income               32576 non-null  Int64
 2   person_home_ownership       32576 non-null  object
 3   person_emp_length           32576 non-null  Int64
 4   loan_intent                 32576 non-null  object
 5   loan_grade                  32576 non-null  object
 6   loan_amnt                   32576 non-null  Int64
 7   loan_int_rate               32576 non-null  Float64
 8   loan_status                 32576 non-null  Int64
 9   loan_percent_income         32576 non-null  Float64
 10  cb_person_default_on_file   32576 non-null  object
 11  cb_person_cred_hist_length  32576 non-null  Int64
dtypes: Float64(2), Int64(6), object(4)
memory usage: 3.5+ MB

In [25]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
person_age,32576.0,27.718044,6.20499,20.0,23.0,26.0,30.0,94.0
person_income,32576.0,65882.14127,52534.987497,4000.0,38500.0,55000.0,79200.0,2039784.0
person_emp_length,32576.0,4.767835,4.087437,0.0,2.0,4.0,7.0,123.0
loan_amnt,32576.0,9589.117755,6321.886846,500.0,5000.0,8000.0,12200.0,35000.0
loan_int_rate,32576.0,11.009486,3.081794,5.42,8.49,10.99,13.11,23.22
loan_status,32576.0,0.218197,0.413029,0.0,0.0,0.0,0.0,1.0
loan_percent_income,32576.0,0.170212,0.106778,0.0,0.09,0.15,0.23,0.83
cb_person_cred_hist_length,32576.0,5.803966,4.053791,2.0,3.0,4.0,8.0,30.0

In [26]:
df[df["person_emp_length"] > 30]

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123,PERSONAL,D,35000,16.02,1,0.59,Y,3
210,21,192000,MORTGAGE,123,VENTURE,A,20000,6.54,0,0.1,N,4
30914,48,70000,MORTGAGE,31,HOMEIMPROVEMENT,D,9000,14.54,0,0.13,N,17
31866,47,178000,OWN,31,VENTURE,B,9000,10.99,0,0.05,N,17
31867,46,180000,MORTGAGE,31,VENTURE,B,18000,9.91,0,0.1,N,11
32263,46,180000,MORTGAGE,31,MEDICAL,B,18000,9.91,0,0.1,N,12
32355,78,48000,RENT,41,MEDICAL,A,3000,7.51,0,0.06,N,25
32428,58,49000,MORTGAGE,34,MEDICAL,D,7500,13.55,1,0.15,Y,24
32515,53,106000,MORTGAGE,38,PERSONAL,B,20000,9.88,0,0.19,N,23

In [27]:
df.drop(df[df["person_emp_length"] > 100].index, inplace=True)

In [28]:
df["loan_status"] = df["loan_status"].astype("object")

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32574 entries, 1 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32574 non-null  Int64
 1   person_income               32574 non-null  Int64
 2   person_home_ownership       32574 non-null  object
 3   person_emp_length           32574 non-null  Int64
 4   loan_intent                 32574 non-null  object
 5   loan_grade                  32574 non-null  object
 6   loan_amnt                   32574 non-null  Int64
 7   loan_int_rate               32574 non-null  Float64
 8   loan_status                 32574 non-null  object
 9   loan_percent_income         32574 non-null  Float64
 10  cb_person_default_on_file   32574 non-null  object
 11  cb_person_cred_hist_length  32574 non-null  Int64
dtypes: Float64(2), Int64(5), object(5)
memory usage: 3.4+ MB

In [30]:
df.to_csv("../data/credit_risk_dataset_cleaned.csv", index=False)